// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {web} from '../models';
import {singbox} from '../models';

export function ActivateFallback(arg1:string):Promise<void>;

export function AdBlockToggleAllowlist(arg1:string,arg2:boolean):Promise<void>;

export function AddBypassDomain(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function AddNode(arg1:string):Promise<void>;

export function AddNodeManual(arg1:models.Node):Promise<void>;

export function AddPaidProvider(arg1:models.PaidProviderEntry):Promise<void>;

export function AutoSelectFallback():Promise<string>;

export function AutoSelectShadowTLSSNI():Promise<string>;

export function CheckCurrentIP():Promise<Record<string, any>>;

export function CheckDomainRouting(arg1:string):Promise<Array<web.DomainRouteResult>>;

export function Connect():Promise<void>;

export function ConnectChainPartner(arg1:string):Promise<models.Node>;

export function Disconnect():Promise<void>;

export function EmergencyWipe(arg1:boolean,arg2:string):Promise<Record<string, any>>;

export function ForceRescan():Promise<void>;

export function ForceSwitch():Promise<void>;

export function GetAdBlockStatus():Promise<Record<string, any>>;

export function GetAntiBlockStatus():Promise<Record<string, any>>;

export function GetBypassRules():Promise<Array<Record<string, any>>>;

export function GetCatalogStatus():Promise<Array<Record<string, any>>>;

export function GetConfig():Promise<models.AppConfig>;

export function GetDPIStatus():Promise<Record<string, any>>;

export function GetDataDir():Promise<string>;

export function GetFallbackStatus():Promise<Record<string, any>>;

export function GetLeakGuardStatus():Promise<Record<string, any>>;

export function GetNodes():Promise<Array<models.Node>>;

export function GetPinnedNodeID():Promise<string>;

export function GetSessionStatus():Promise<Record<string, any>>;

export function GetSingBoxInfo():Promise<Record<string, any>>;

export function GetState():Promise<models.ConnectionState>;

export function GetStats():Promise<Record<string, number>>;

export function GetUptime():Promise<string>;

export function GetVersion():Promise<string>;

export function GetWatchdogStatus():Promise<Record<string, any>>;

export function MinimizeWindow():Promise<void>;

export function OpenBrowser(arg1:string):Promise<void>;

// V13-5-wails (ТЗ v1.4, F5.5): возвращает ключи конфига, требующие перезапуска APF
// (пусто — применилось сразу). Раньше Promise<void> — needs_restart молча терялся.
export function PatchConfig(arg1:Record<string, any>):Promise<Array<string>>;

export function PinNode(arg1:string):Promise<void>;

export function RefreshCatalog():Promise<number>;

export function RemoveBypassDomain(arg1:string):Promise<void>;

export function RemovePaidProvider(arg1:string):Promise<void>;

export function RunCanaryTest():Promise<Record<string, any>>;

export function RunDNSLeakTest():Promise<Record<string, any>>;

export function ServerRoleBuildLink(arg1:Record<string, any>,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function ServerRoleDetectReachability(arg1:number):Promise<Record<string, any>>;

export function ServerRoleGenerateIdentity():Promise<Record<string, any>>;

export function ServerRoleLoadIdentity():Promise<Record<string, any>>;

// S-3-frontend (ТЗ v1.4): дописано вручную, см. App.js.
export function ServerRoleExportIdentity():Promise<Record<string, any>>;

export function ServerRoleLocalIPCandidates():Promise<Array<singbox.LocalIPCandidate>>;

export function ServerRoleStart(arg1:Record<string, any>,arg2:number,arg3:string):Promise<void>;

export function ServerRoleStatus():Promise<Record<string, any>>;

export function ServerRoleStop():Promise<void>;

export function SetAdBlockProfile(arg1:string):Promise<void>;

export function SetAntiBlockConfig(arg1:boolean,arg2:boolean,arg3:boolean,arg4:string):Promise<void>;

export function SetBypassRule(arg1:string,arg2:boolean):Promise<void>;

export function SetCDNConfig(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetCatalogProviderEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function SetShadowTLSConfig(arg1:boolean,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetStickyPolicy(arg1:string):Promise<void>;

export function SetTrafficPadding(arg1:boolean,arg2:boolean):Promise<void>;

export function SetWebRTCBlock(arg1:boolean):Promise<void>;

export function TestPaidProvider(arg1:models.PaidProviderEntry):Promise<number>;

export function UnpinNode():Promise<void>;

export function UpdateBypassDomain(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

// ТЗ v1.3 F2 (2026-09-05): дописано вручную, см. App.js.
export function ConnectOnce(arg1:string):Promise<void>;
export function AddFavorite(arg1:string):Promise<void>;
export function RemoveFavorite(arg1:string):Promise<void>;
export function GetFavoriteIDs():Promise<Array<string>>;
// ТЗ v1.3 F5.1 (2026-09-05): дописано вручную, см. App.js.
export function ExportLog():Promise<string>;
export function OpenLogFolder():Promise<void>;
export function GetLogFilePath():Promise<string>;
// ТЗ v1.3 F3 (2026-09-05): дописано вручную, см. App.js.
export function RemoveNode(arg1:string):Promise<void>;
export function BanNode(arg1:string,arg2:boolean):Promise<void>;
export function UpdateNode(arg1:string,arg2:string,arg3:string):Promise<void>;
export function ResetNodeStats(arg1:string):Promise<void>;
export function RestoreRemovedNodes():Promise<number>;
export function GetRemovedNodeIDs():Promise<Array<string>>;
// ТЗ v1.3 F4 Stage 1 (2026-09-05): дописано вручную, см. App.js.
export function StartSweep():Promise<void>;
export function CancelSweep():Promise<void>;
export function GetScanProgress():Promise<any>;
// S-2/U-17-desktop (ТЗ v1.4, 2026-09-08): дописано вручную, см. App.js.
export function OpenWebUI():Promise<void>;
export function GetLastPersistError():Promise<string>;
// N-3 (ТЗ APF v1.5, лот L2-WAILS, 2026-09-14): проба реального трафика — «Собрать список
// рабочих узлов» — дописано вручную, см. App.js.
export function StartNodeCheck():Promise<void>;
export function CancelNodeCheck():Promise<void>;
export function NodeCheckStatus():Promise<any>;
// L5-UI (ТЗ v1.4 §5, 2026-09-15): ручной харвест — дописано вручную, см. App.js/gui/app.go.
export function HarvestNow():Promise<void>;
export function HarvestStatus():Promise<any>;
// W5 paste-харвест — дописано вручную 2026-09-23, см. App.js/gui/app.go.
export function HarvestFromText(arg1:string):Promise<void>;
// W3 (ТЗ APF v1.5 §2/§5, лот L2-WAILS-B, 2026-09-14): дописано вручную, см. App.js.
export function FavoriteOrigin(arg1:string):Promise<string>;
export function UserFavoriteIDs():Promise<Array<string>>;
export function SystemFavoriteIDs():Promise<Array<string>>;
export function CatalogReviewInterval():Promise<string>;
export function SetCatalogReviewInterval(arg1:string):Promise<void>;