// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateFallback(arg1) {
  return window['go']['main']['App']['ActivateFallback'](arg1);
}

export function AdBlockToggleAllowlist(arg1, arg2) {
  return window['go']['main']['App']['AdBlockToggleAllowlist'](arg1, arg2);
}

export function AddBypassDomain(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddBypassDomain'](arg1, arg2, arg3, arg4);
}

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function AddNodeManual(arg1) {
  return window['go']['main']['App']['AddNodeManual'](arg1);
}

export function AddPaidProvider(arg1) {
  return window['go']['main']['App']['AddPaidProvider'](arg1);
}

export function AutoSelectFallback() {
  return window['go']['main']['App']['AutoSelectFallback']();
}

export function AutoSelectShadowTLSSNI() {
  return window['go']['main']['App']['AutoSelectShadowTLSSNI']();
}

export function CheckCurrentIP() {
  return window['go']['main']['App']['CheckCurrentIP']();
}

export function CheckDomainRouting(arg1) {
  return window['go']['main']['App']['CheckDomainRouting'](arg1);
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function ConnectChainPartner(arg1) {
  return window['go']['main']['App']['ConnectChainPartner'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EmergencyWipe(arg1, arg2) {
  return window['go']['main']['App']['EmergencyWipe'](arg1, arg2);
}

export function ForceRescan() {
  return window['go']['main']['App']['ForceRescan']();
}

export function ForceSwitch() {
  return window['go']['main']['App']['ForceSwitch']();
}

export function GetAdBlockStatus() {
  return window['go']['main']['App']['GetAdBlockStatus']();
}

export function GetAntiBlockStatus() {
  return window['go']['main']['App']['GetAntiBlockStatus']();
}

export function GetBypassRules() {
  return window['go']['main']['App']['GetBypassRules']();
}

export function GetCatalogStatus() {
  return window['go']['main']['App']['GetCatalogStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDPIStatus() {
  return window['go']['main']['App']['GetDPIStatus']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetFallbackStatus() {
  return window['go']['main']['App']['GetFallbackStatus']();
}

export function GetLeakGuardStatus() {
  return window['go']['main']['App']['GetLeakGuardStatus']();
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetPinnedNodeID() {
  return window['go']['main']['App']['GetPinnedNodeID']();
}

export function GetSessionStatus() {
  return window['go']['main']['App']['GetSessionStatus']();
}

export function GetSingBoxInfo() {
  return window['go']['main']['App']['GetSingBoxInfo']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUptime() {
  return window['go']['main']['App']['GetUptime']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWatchdogStatus() {
  return window['go']['main']['App']['GetWatchdogStatus']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function PatchConfig(arg1) {
  return window['go']['main']['App']['PatchConfig'](arg1);
}

export function PinNode(arg1) {
  return window['go']['main']['App']['PinNode'](arg1);
}

export function RefreshCatalog() {
  return window['go']['main']['App']['RefreshCatalog']();
}

export function RemoveBypassDomain(arg1) {
  return window['go']['main']['App']['RemoveBypassDomain'](arg1);
}

export function RemovePaidProvider(arg1) {
  return window['go']['main']['App']['RemovePaidProvider'](arg1);
}

export function RunCanaryTest() {
  return window['go']['main']['App']['RunCanaryTest']();
}

export function RunDNSLeakTest() {
  return window['go']['main']['App']['RunDNSLeakTest']();
}

export function ServerRoleBuildLink(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ServerRoleBuildLink'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ServerRoleDetectReachability(arg1) {
  return window['go']['main']['App']['ServerRoleDetectReachability'](arg1);
}

export function ServerRoleGenerateIdentity() {
  return window['go']['main']['App']['ServerRoleGenerateIdentity']();
}

export function ServerRoleLoadIdentity() {
  return window['go']['main']['App']['ServerRoleLoadIdentity']();
}

// S-3-frontend (ТЗ v1.4): дописано вручную (wails generate на хосте запрещён) — приватный
// ключ звена целиком, только под явным подтверждением (см. gui/app.go).
export function ServerRoleExportIdentity() {
  return window['go']['main']['App']['ServerRoleExportIdentity']();
}

export function ServerRoleLocalIPCandidates() {
  return window['go']['main']['App']['ServerRoleLocalIPCandidates']();
}

export function ServerRoleStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServerRoleStart'](arg1, arg2, arg3);
}

export function ServerRoleStatus() {
  return window['go']['main']['App']['ServerRoleStatus']();
}

export function ServerRoleStop() {
  return window['go']['main']['App']['ServerRoleStop']();
}

export function SetAdBlockProfile(arg1) {
  return window['go']['main']['App']['SetAdBlockProfile'](arg1);
}

export function SetAntiBlockConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAntiBlockConfig'](arg1, arg2, arg3, arg4);
}

export function SetBypassRule(arg1, arg2) {
  return window['go']['main']['App']['SetBypassRule'](arg1, arg2);
}

export function SetCDNConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCDNConfig'](arg1, arg2, arg3);
}

export function SetCatalogProviderEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetCatalogProviderEnabled'](arg1, arg2);
}

export function SetMasterPassword(arg1) {
  return window['go']['main']['App']['SetMasterPassword'](arg1);
}

export function SetShadowTLSConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetShadowTLSConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetStickyPolicy(arg1) {
  return window['go']['main']['App']['SetStickyPolicy'](arg1);
}

export function SetTrafficPadding(arg1, arg2) {
  return window['go']['main']['App']['SetTrafficPadding'](arg1, arg2);
}

export function SetWebRTCBlock(arg1) {
  return window['go']['main']['App']['SetWebRTCBlock'](arg1);
}

export function TestPaidProvider(arg1) {
  return window['go']['main']['App']['TestPaidProvider'](arg1);
}

export function UnpinNode() {
  return window['go']['main']['App']['UnpinNode']();
}

export function UpdateBypassDomain(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateBypassDomain'](arg1, arg2, arg3, arg4, arg5);
}

// ТЗ v1.3 F2 (2026-09-05): биндинги дописаны вручную — wails generate на хосте запрещён
// (исполняет реальный бинарник, см. память wails-generate-executes-real-app).
export function ConnectOnce(arg1) {
  return window['go']['main']['App']['ConnectOnce'](arg1);
}

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function GetFavoriteIDs() {
  return window['go']['main']['App']['GetFavoriteIDs']();
}
// ТЗ v1.3 F5.1 (2026-09-05): экспорт лога — дописано вручную (wails generate на хосте запрещён).
export function ExportLog() {
  return window['go']['main']['App']['ExportLog']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}
// ТЗ v1.3 F3 (2026-09-05): управление узлами — дописано вручную (wails generate на хосте запрещён).
export function RemoveNode(arg1) {
  return window['go']['main']['App']['RemoveNode'](arg1);
}

export function BanNode(arg1, arg2) {
  return window['go']['main']['App']['BanNode'](arg1, arg2);
}

export function UpdateNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNode'](arg1, arg2, arg3);
}

export function ResetNodeStats(arg1) {
  return window['go']['main']['App']['ResetNodeStats'](arg1);
}

export function RestoreRemovedNodes() {
  return window['go']['main']['App']['RestoreRemovedNodes']();
}

export function GetRemovedNodeIDs() {
  return window['go']['main']['App']['GetRemovedNodeIDs']();
}
// ТЗ v1.3 F4 Stage 1 (2026-09-05): обход пула — дописано вручную (wails generate на хосте запрещён).
export function StartSweep() {
  return window['go']['main']['App']['StartSweep']();
}

export function CancelSweep() {
  return window['go']['main']['App']['CancelSweep']();
}

export function GetScanProgress() {
  return window['go']['main']['App']['GetScanProgress']();
}

// S-2 (ТЗ v1.4, лот L1b-CLI): OpenWebUI — Go-метод существовал и был протестирован, но не
// был подключён во фронт ни одним лотом (открытый вопрос L1b-CLI, result.md). L2-D дописывает
// биндинг вручную (wails generate на хосте запрещён) и подключает кнопку «Открыть Web UI».
export function OpenWebUI() {
  return window['go']['main']['App']['OpenWebUI']();
}

// U-17-desktop (ТЗ v1.4, §7.2 контракта): предупреждение «узлы не сохранены: <причина>».
export function GetLastPersistError() {
  return window['go']['main']['App']['GetLastPersistError']();
}

// N-3 (ТЗ APF v1.5, лот L2-WAILS, 2026-09-14): проба реального трафика — «Собрать список
// рабочих узлов» — дописано вручную (wails generate на хосте запрещён, apf-never-run-on-host).
export function StartNodeCheck() {
  return window['go']['main']['App']['StartNodeCheck']();
}

export function CancelNodeCheck() {
  return window['go']['main']['App']['CancelNodeCheck']();
}

export function NodeCheckStatus() {
  return window['go']['main']['App']['NodeCheckStatus']();
}

// L5-UI (ТЗ v1.4 §5, 2026-09-15): ручной харвест узлов из источников — дописано вручную
// (wails generate на хосте запрещён), см. gui/app.go HarvestNow/HarvestStatus.
export function HarvestNow() {
  return window['go']['main']['App']['HarvestNow']();
}

export function HarvestStatus() {
  return window['go']['main']['App']['HarvestStatus']();
}

// W5 paste-харвест (2026-09-21): извлечение узлов из вставленного текста — дописано вручную
// 2026-09-23 (wails generate на хосте запрещён), см. gui/app.go HarvestFromText.
export function HarvestFromText(arg1) {
  return window['go']['main']['App']['HarvestFromText'](arg1);
}

// W3 (ТЗ APF v1.5 §2/§5, лот L2-WAILS-B, 2026-09-14): двухклассовое избранное (user/system) +
// интервал пересмотра каталога — дописано вручную (wails generate на хосте запрещён), см.
// gui/app.go.
export function FavoriteOrigin(arg1) {
  return window['go']['main']['App']['FavoriteOrigin'](arg1);
}

export function UserFavoriteIDs() {
  return window['go']['main']['App']['UserFavoriteIDs']();
}

export function SystemFavoriteIDs() {
  return window['go']['main']['App']['SystemFavoriteIDs']();
}

export function CatalogReviewInterval() {
  return window['go']['main']['App']['CatalogReviewInterval']();
}

export function SetCatalogReviewInterval(arg1) {
  return window['go']['main']['App']['SetCatalogReviewInterval'](arg1);
}